<a href="https://colab.research.google.com/github/bhagyasree2004/MachineLearning_Module/blob/main/CLASSIFICATION_MODELS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Contract'] = le.fit_transform(df['Contract'])

In [ ]:
df.TotalCharges=pd.to_numeric(df.TotalCharges,errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   int64
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(3), object(16)
memory usage: 1.1+ MB

In [ ]:
df.dropna(how='any',inplace=True)

In [ ]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,0,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,1,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,0,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,1,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,0,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df['Churn'].value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [ ]:
x=df.drop(["customerID","Churn"],axis=1)

In [ ]:

x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,0,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,1,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,0,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,1,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,0,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,1,Yes,Mailed check,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,1,Yes,Credit card (automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,0,Yes,Electronic check,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,0,Yes,Mailed check,74.40,306.60
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,2,Yes,Bank transfer (automatic),105.65,6844.50

In [ ]:
y=df.Churn.values

In [ ]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'], dtype=object)

In [ ]:
print(x.columns)

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [ ]:
#convert categorical column into numewrical features

x = pd.get_dummies(
    x,
    columns=[
        'gender', 'Partner', 'Dependents', 'PhoneService',
        'MultipleLines', 'InternetService', 'OnlineSecurity',
        'OnlineBackup', 'DeviceProtection', 'TechSupport',
        'StreamingTV', 'StreamingMovies', 'Contract',
        'PaperlessBilling', 'PaymentMethod'
    ],
    drop_first=True
)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
len(x_train)

5274

In [ ]:
len(x_test)

1758

In [ ]:
#feature scaling

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
x_train

array([[-0.43679284,  1.62814876,  1.46066229, ..., -0.52513044,
        -0.72011932, -0.54301809],
       [-0.43679284,  1.46485552, -1.4956825 , ..., -0.52513044,
        -0.72011932, -0.54301809],
       [-0.43679284, -0.86207312,  0.81239954, ..., -0.52513044,
         1.38865875, -0.54301809],
       ...,
       [-0.43679284,  0.73003595,  1.37067209, ...,  1.90428879,
        -0.72011932, -0.54301809],
       [-0.43679284, -0.73960319,  0.52076462, ...,  1.90428879,
        -0.72011932, -0.54301809],
       [-0.43679284,  1.30156228,  1.32734347, ...,  1.90428879,
        -0.72011932, -0.54301809]])

In [ ]:
x_test

array([[-0.43679284, -1.27030621, -1.4723517 , ..., -0.52513044,
         1.38865875, -0.54301809],
       [-0.43679284, -0.65795657, -1.47401819, ...,  1.90428879,
        -0.72011932, -0.54301809],
       [-0.43679284, -1.27030621, -1.50068195, ...,  1.90428879,
        -0.72011932, -0.54301809],
       ...,
       [-0.43679284, -1.27030621, -0.34914066, ..., -0.52513044,
         1.38865875, -0.54301809],
       [ 2.2894148 ,  0.89332919,  0.01415312, ..., -0.52513044,
        -0.72011932, -0.54301809],
       [-0.43679284,  0.81168257, -1.49901547, ..., -0.52513044,
        -0.72011932,  1.84155927]])

In [ ]:
# KNN
#call the knn classifier
from sklearn.neighbors import KNeighborsClassifier

#initiating the classifier
model=KNeighborsClassifier()

#passing the data
model.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
#predictions
y_pred=model.predict(x_test)

In [ ]:
y_pred

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
y_test

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix =to check the model is behaving /accuracy

from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1117,  194],
       [ 226,  221]])

In [ ]:
#accuracy score
accuracy_score(y_test,y_pred)

0.7610921501706485

In [ ]:
#accurcay score
accuracy_score(y_test,y_pred)*100

76.10921501706484

In [ ]:
#new data prediction

x_test[0]

array([-0.43679284, -1.27030621, -1.4723517 , -0.993177  ,  0.9943278 ,
       -0.96313632, -0.65370807,  0.32860796, -0.32860796, -0.8562465 ,
       -0.88860371,  1.90749113,  1.90749113, -0.63044134,  1.90749113,
       -0.72376587,  1.90749113, -0.71981575,  1.90749113, -0.63337901,
        1.90749113, -0.79327573,  1.90749113, -0.80314416, -0.51335775,
       -0.55500965, -1.21828586, -0.52513044,  1.38865875, -0.54301809])

In [ ]:
data=[[0,2,87,178,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,2,1,0,0,1,2,3]]

In [ ]:
data_sc=sc.transform(data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [ ]:
single=model.predict(data_sc)
print(single)

['No']

In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
y_test

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1066,  245],
       [ 231,  216]])

In [ ]:
#ACCURACY SCORE

accuracy_score(y_test,y_pred)*100

72.92377701934016

In [ ]:
#entropy and gini index
#entropy used for classification -to find uncertianity

#gini index to find mixed data

In [ ]:
#random forest
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
# confusion tree
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1185,  126],
       [ 237,  210]])

In [ ]:
#accuracy
accuracy_score(y_test,y_pred)*100

79.35153583617748

In [ ]:
#SVM
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC()

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1202,  109],
       [ 230,  217]])

In [ ]:
#accuracy score
accuracy_score(y_test,y_pred)*100

80.71672354948805

In [ ]:
#ensemble learning-boosting
#gradient boosting
#extreme gradient boosting(XG Boost)
#Ada boost
#Catboost

In [ ]:
#call the AdaBoost Clasifier
from sklearn.ensemble import AdaBoostClassifier
model=AdaBoostClassifier(n_estimators=100)
model.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=100)

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1191,  120],
       [ 226,  221]])

In [ ]:
#accuracy score
accuracy_score(y_test,y_pred)*100

80.31854379977247

In [ ]:
#CatBoost
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 9.4 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [ ]:
#catboost
from catboost import CatBoostClassifier
model=CatBoostClassifier()
model.fit(x_train,y_train)

Learning rate set to 0.020955
0:	learn: 0.6794606	total: 52.9ms	remaining: 52.9s
1:	learn: 0.6675218	total: 58.1ms	remaining: 29s
2:	learn: 0.6552688	total: 64ms	remaining: 21.3s
3:	learn: 0.6434315	total: 71.4ms	remaining: 17.8s
4:	learn: 0.6324935	total: 77.5ms	remaining: 15.4s
5:	learn: 0.6221416	total: 84.1ms	remaining: 13.9s
6:	learn: 0.6112441	total: 89.7ms	remaining: 12.7s
7:	learn: 0.6006928	total: 96.1ms	remaining: 11.9s
8:	learn: 0.5905683	total: 102ms	remaining: 11.2s
9:	learn: 0.5834001	total: 108ms	remaining: 10.7s
10:	learn: 0.5749857	total: 114ms	remaining: 10.2s
11:	learn: 0.5676071	total: 120ms	remaining: 9.85s
12:	learn: 0.5600802	total: 124ms	remaining: 9.43s
13:	learn: 0.5533950	total: 129ms	remaining: 9.08s
14:	learn: 0.5472480	total: 134ms	remaining: 8.79s
15:	learn: 0.5410152	total: 139ms	remaining: 8.53s
16:	learn: 0.5354258	total: 144ms	remaining: 8.3s
17:	learn: 0.5298523	total: 148ms	remaining: 8.09s
18:	learn: 0.5246564	total: 156ms	remaining: 8.04s
19:	learn: 0.5197228	total: 164ms	remaining: 8.05s
20:	learn: 0.5152618	total: 170ms	remaining: 7.93s
21:	learn: 0.5108440	total: 176ms	remaining: 7.82s
22:	learn: 0.5066219	total: 180ms	remaining: 7.63s
23:	learn: 0.5026885	total: 184ms	remaining: 7.46s
24:	learn: 0.4987365	total: 187ms	remaining: 7.29s
25:	learn: 0.4952580	total: 190ms	remaining: 7.13s
26:	learn: 0.4919181	total: 194ms	remaining: 6.98s
27:	learn: 0.4888120	total: 199ms	remaining: 6.92s
28:	learn: 0.4859037	total: 203ms	remaining: 6.79s
29:	learn: 0.4824370	total: 206ms	remaining: 6.68s
30:	learn: 0.4795240	total: 210ms	remaining: 6.57s
31:	learn: 0.4768401	total: 214ms	remaining: 6.46s
32:	learn: 0.4742015	total: 217ms	remaining: 6.36s
33:	learn: 0.4717892	total: 221ms	remaining: 6.28s
34:	learn: 0.4686625	total: 225ms	remaining: 6.19s
35:	learn: 0.4661276	total: 228ms	remaining: 6.11s
36:	learn: 0.4635924	total: 232ms	remaining: 6.04s
37:	learn: 0.4610631	total: 236ms	remaining: 5.97s
38:	learn: 0.4591705	total: 240ms	remaining: 5.91s
39:	learn: 0.4570006	total: 243ms	remaining: 5.84s
40:	learn: 0.4546747	total: 247ms	remaining: 5.78s
41:	learn: 0.4528216	total: 251ms	remaining: 5.71s
42:	learn: 0.4513377	total: 254ms	remaining: 5.66s
43:	learn: 0.4500116	total: 258ms	remaining: 5.6s
44:	learn: 0.4487070	total: 261ms	remaining: 5.54s
45:	learn: 0.4472292	total: 265ms	remaining: 5.5s
46:	learn: 0.4457301	total: 269ms	remaining: 5.45s
47:	learn: 0.4443964	total: 272ms	remaining: 5.4s
48:	learn: 0.4431706	total: 276ms	remaining: 5.35s
49:	learn: 0.4418408	total: 279ms	remaining: 5.31s
50:	learn: 0.4400921	total: 283ms	remaining: 5.26s
51:	learn: 0.4388859	total: 286ms	remaining: 5.22s
52:	learn: 0.4376037	total: 290ms	remaining: 5.18s
53:	learn: 0.4365088	total: 295ms	remaining: 5.16s
54:	learn: 0.4355414	total: 302ms	remaining: 5.19s
55:	learn: 0.4345019	total: 306ms	remaining: 5.16s
56:	learn: 0.4336584	total: 309ms	remaining: 5.12s
57:	learn: 0.4322679	total: 313ms	remaining: 5.08s
58:	learn: 0.4313777	total: 317ms	remaining: 5.06s
59:	learn: 0.4305072	total: 321ms	remaining: 5.03s
60:	learn: 0.4295546	total: 324ms	remaining: 4.99s
61:	learn: 0.4286052	total: 328ms	remaining: 4.96s
62:	learn: 0.4277440	total: 332ms	remaining: 4.93s
63:	learn: 0.4268765	total: 335ms	remaining: 4.91s
64:	learn: 0.4259560	total: 339ms	remaining: 4.88s
65:	learn: 0.4251493	total: 342ms	remaining: 4.84s
66:	learn: 0.4244033	total: 346ms	remaining: 4.82s
67:	learn: 0.4237509	total: 349ms	remaining: 4.79s
68:	learn: 0.4231879	total: 353ms	remaining: 4.76s
69:	learn: 0.4226336	total: 356ms	remaining: 4.73s
70:	learn: 0.4218969	total: 360ms	remaining: 4.71s
71:	learn: 0.4213381	total: 363ms	remaining: 4.68s
72:	learn: 0.4206060	total: 366ms	remaining: 4.65s
73:	learn: 0.4199976	total: 370ms	remaining: 4.63s
74:	learn: 0.4191730	total: 373ms	remaining: 4.6s
75:	learn: 0.4185596	total: 377ms	remaining: 4.58s
76:	learn: 0.4179626	total: 380ms	remaining: 4.55s
77:	learn: 0.4172802	total: 384ms	remaining: 4.53s
78:	learn: 0.4168093	total: 387ms	remaining: 4.51s
79:	learn: 0.4160647	total: 390ms	remaining: 4.49s
80:	learn: 0.4154055	total: 395ms	remaining: 4.48s
81:	learn: 0.4146637	total: 401ms	remaining: 4.49s
82:	learn: 0.4141679	total: 404ms	remaining: 4.47s
83:	learn: 0.4137768	total: 408ms	remaining: 4.45s
84:	learn: 0.4133397	total: 412ms	remaining: 4.43s
85:	learn: 0.4128423	total: 416ms	remaining: 4.42s
86:	learn: 0.4124133	total: 420ms	remaining: 4.4s
87:	learn: 0.4117179	total: 423ms	remaining: 4.38s
88:	learn: 0.4113576	total: 426ms	remaining: 4.36s
89:	learn: 0.4108573	total: 431ms	remaining: 4.36s
90:	learn: 0.4102812	total: 435ms	remaining: 4.35s
91:	learn: 0.4097991	total: 439ms	remaining: 4.33s
92:	learn: 0.4095495	total: 442ms	remaining: 4.31s
93:	learn: 0.4090186	total: 445ms	remaining: 4.29s
94:	learn: 0.4086574	total: 449ms	remaining: 4.27s
95:	learn: 0.4083727	total: 452ms	remaining: 4.26s
96:	learn: 0.4080502	total: 456ms	remaining: 4.24s
97:	learn: 0.4077672	total: 460ms	remaining: 4.23s
98:	learn: 0.4073994	total: 464ms	remaining: 4.22s
99:	learn: 0.4069466	total: 468ms	remaining: 4.21s
100:	learn: 0.4065125	total: 476ms	remaining: 4.23s
101:	learn: 0.4061846	total: 479ms	remaining: 4.22s
102:	learn: 0.4058216	total: 483ms	remaining: 4.2s
103:	learn: 0.4055503	total: 486ms	remaining: 4.19s
104:	learn: 0.4051631	total: 490ms	remaining: 4.17s
105:	learn: 0.4048648	total: 493ms	remaining: 4.16s
106:	learn: 0.4047026	total: 495ms	remaining: 4.13s
107:	learn: 0.4044715	total: 499ms	remaining: 4.12s
108:	learn: 0.4041453	total: 502ms	remaining: 4.11s
109:	learn: 0.4037567	total: 506ms	remaining: 4.09s
110:	learn: 0.4032429	total: 509ms	remaining: 4.08s
111:	learn: 0.4028895	total: 513ms	remaining: 4.06s
112:	learn: 0.4025279	total: 516ms	remaining: 4.05s
113:	learn: 0.4022143	total: 519ms	remaining: 4.04s
114:	learn: 0.4018488	total: 523ms	remaining: 4.02s
115:	learn: 0.4015142	total: 526ms	remaining: 4.01s
116:	learn: 0.4011704	total: 530ms	remaining: 4s
117:	learn: 0.4008466	total: 533ms	remaining: 3.98s
118:	learn: 0.4005938	total: 536ms	remaining: 3.97s
119:	learn: 0.4001574	total: 540ms	remaining: 3.96s
120:	learn: 0.3998514	total: 543ms	remaining: 3.95s
121:	learn: 0.3995251	total: 547ms	remaining: 3.93s
122:	learn: 0.3993019	total: 550ms	remaining: 3.92s
123:	learn: 0.3990608	total: 555ms	remaining: 3.92s
124:	learn: 0.3987714	total: 559ms	remaining: 3.91s
125:	learn: 0.3984999	total: 562ms	remaining: 3.9s
126:	learn: 0.3982868	total: 566ms	remaining: 3.89s
127:	learn: 0.3980874	total: 569ms	remaining: 3.88s
128:	learn: 0.3976665	total: 573ms	remaining: 3.87s
129:	learn: 0.3973504	total: 576ms	remaining: 3.85s
130:	learn: 0.3970957	total: 579ms	remaining: 3.84s
131:	learn: 0.3969150	total: 583ms	remaining: 3.83s
132:	learn: 0.3966390	total: 587ms	remaining: 3.83s
133:	learn: 0.3964828	total: 594ms	remaining: 3.84s
134:	learn: 0.3962007	total: 597ms	remaining: 3.83s
135:	learn: 0.3960556	total: 601ms	remaining: 3.81s
136:	learn: 0.3956959	total: 604ms	remaining: 3.81s
137:	learn: 0.3953848	total: 608ms	remaining: 3.8s
138:	learn: 0.3952260	total: 611ms	remaining: 3.79s
139:	learn: 0.3950908	total: 614ms	remaining: 3.77s
140:	learn: 0.3949308	total: 617ms	remaining: 3.76s
141:	learn: 0.3947894	total: 621ms	remaining: 3.75s
142:	learn: 0.3945635	total: 624ms	remaining: 3.74s
143:	learn: 0.3944251	total: 627ms	remaining: 3.73s
144:	learn: 0.3940927	total: 631ms	remaining: 3.72s
145:	learn: 0.3938384	total: 635ms	remaining: 3.71s
146:	learn: 0.3937028	total: 639ms	remaining: 3.71s
147:	learn: 0.3935465	total: 642ms	remaining: 3.7s
148:	learn: 0.3933300	total: 646ms	remaining: 3.69s
149:	learn: 0.3931008	total: 649ms	remaining: 3.68s
150:	learn: 0.3928985	total: 653ms	remaining: 3.67s
151:	learn: 0.3926811	total: 656ms	remaining: 3.66s
152:	learn: 0.3924552	total: 660ms	remaining: 3.65s
153:	learn: 0.3922674	total: 663ms	remaining: 3.64s
154:	learn: 0.3921002	total: 667ms	remaining: 3.63s
155:	learn: 0.3918650	total: 670ms	remaining: 3.63s
156:	learn: 0.3916793	total: 674ms	remaining: 3.62s
157:	learn: 0.3915003	total: 678ms	remaining: 3.61s
158:	learn: 0.3912594	total: 685ms	remaining: 3.62s
159:	learn: 0.3909723	total: 690ms	remaining: 3.62s
160:	learn: 0.3907957	total: 695ms	remaining: 3.62s
161:	learn: 0.3904800	total: 701ms	remaining: 3.62s
162:	learn: 0.3902312	total: 706ms	remaining: 3.62s
163:	learn: 0.3900103	total: 711ms	remaining: 3.63s
164:	learn: 0.3898635	total: 715ms	remaining: 3.62s
165:	learn: 0.3896679	total: 718ms	remaining: 3.61s
166:	learn: 0.3894499	total: 722ms	remaining: 3.6s
167:	learn: 0.3892377	total: 730ms	remaining: 3.61s
168:	learn: 0.3889594	total: 737ms	remaining: 3.62s
169:	learn: 0.3888234	total: 742ms	remaining: 3.62s
170:	learn: 0.3886585	total: 747ms	remaining: 3.62s
171:	learn: 0.3883921	total: 753ms	remaining: 3.62s
172:	learn: 0.3881042	total: 758ms	remaining: 3.62s
173:	learn: 0.3880284	total: 763ms	remaining: 3.62s
174:	learn: 0.3878302	total: 769ms	remaining: 3.63s
175:	learn: 0.3876650	total: 774ms	remaining: 3.62s
176:	learn: 0.3874828	total: 780ms	remaining: 3.63s
177:	learn: 0.3873534	total: 793ms	remaining: 3.66s
178:	learn: 0.3871045	total: 805ms	remaining: 3.69s
179:	learn: 0.3869399	total: 814ms	remaining: 3.71s
180:	learn: 0.3867054	total: 819ms	remaining: 3.71s
181:	learn: 0.3866251	total: 826ms	remaining: 3.71s
182:	learn: 0.3864997	total: 831ms	remaining: 3.71s
183:	learn: 0.3863134	total: 838ms	remaining: 3.72s
184:	learn: 0.3861088	total: 846ms	remaining: 3.73s
185:	learn: 0.3859450	total: 853ms	remaining: 3.73s
186:	learn: 0.3857914	total: 858ms	remaining: 3.73s
187:	learn: 0.3855986	total: 865ms	remaining: 3.74s
188:	learn: 0.3853366	total: 871ms	remaining: 3.74s
189:	learn: 0.3851602	total: 877ms	remaining: 3.74s
190:	learn: 0.3850615	total: 882ms	remaining: 3.73s
191:	learn: 0.3849178	total: 887ms	remaining: 3.73s
192:	learn: 0.3847773	total: 895ms	remaining: 3.74s
193:	learn: 0.3846672	total: 901ms	remaining: 3.74s
194:	learn: 0.3844786	total: 906ms	remaining: 3.74s
195:	learn: 0.3842980	total: 911ms	remaining: 3.74s
196:	learn: 0.3841251	total: 917ms	remaining: 3.74s
197:	learn: 0.3839862	total: 923ms	remaining: 3.74s
198:	learn: 0.3838571	total: 932ms	remaining: 3.75s
199:	learn: 0.3836674	total: 940ms	remaining: 3.76s
200:	learn: 0.3834863	total: 953ms	remaining: 3.79s
201:	learn: 0.3832236	total: 964ms	remaining: 3.81s
202:	learn: 0.3830342	total: 975ms	remaining: 3.83s
203:	learn: 0.3829568	total: 986ms	remaining: 3.85s
204:	learn: 0.3828857	total: 999ms	remaining: 3.88s
205:	learn: 0.3827769	total: 1.01s	remaining: 3.9s
206:	learn: 0.3826542	total: 1.02s	remaining: 3.92s
207:	learn: 0.3824259	total: 1.03s	remaining: 3.93s
208:	learn: 0.3822400	total: 1.04s	remaining: 3.95s
209:	learn: 0.3821556	total: 1.05s	remaining: 3.96s
210:	learn: 0.3819999	total: 1.06s	remaining: 3.98s
211:	learn: 0.3818015	total: 1.08s	remaining: 4.01s
212:	learn: 0.3817027	total: 1.09s	remaining: 4.04s
213:	learn: 0.3816848	total: 1.1s	remaining: 4.05s
214:	learn: 0.3815857	total: 1.12s	remaining: 4.08s
215:	learn: 0.3813871	total: 1.14s	remaining: 4.14s
216:	learn: 0.3812689	total: 1.16s	remaining: 4.18s
217:	learn: 0.3811471	total: 1.17s	remaining: 4.2s
218:	learn: 0.3809583	total: 1.19s	remaining: 4.25s
219:	learn: 0.3808170	total: 1.21s	remaining: 4.29s
220:	learn: 0.3806154	total: 1.22s	remaining: 4.32s
221:	learn: 0.3804796	total: 1.24s	remaining: 4.36s
222:	learn: 0.3802570	total: 1.27s	remaining: 4.42s
223:	learn: 0.3801493	total: 1.29s	remaining: 4.46s
224:	learn: 0.3800006	total: 1.29s	remaining: 4.46s
225:	learn: 0.3798430	total: 1.3s	remaining: 4.45s
226:	learn: 0.3796366	total: 1.3s	remaining: 4.44s
227:	learn: 0.3794071	total: 1.31s	remaining: 4.44s
228:	learn: 0.3792598	total: 1.32s	remaining: 4.43s
229:	learn: 0.3791247	total: 1.32s	remaining: 4.43s
230:	learn: 0.3789148	total: 1.33s	remaining: 4.42s
231:	learn: 0.3788056	total: 1.34s	remaining: 4.43s
232:	learn: 0.3787800	total: 1.34s	remaining: 4.43s
233:	learn: 0.3786528	total: 1.36s	remaining: 4.45s
234:	learn: 0.3785019	total: 1.37s	remaining: 4.47s
235:	learn: 0.3784142	total: 1.39s	remaining: 4.5s
236:	learn: 0.3782632	total: 1.4s	remaining: 4.51s
237:	learn: 0.3781256	total: 1.43s	remaining: 4.58s
238:	learn: 0.3779607	total: 1.45s	remaining: 4.61s
239:	learn: 0.3778341	total: 1.47s	remaining: 4.66s
240:	learn: 0.3776949	total: 1.49s	remaining: 4.69s
241:	learn: 0.3776020	total: 1.49s	remaining: 4.68s
242:	learn: 0.3774427	total: 1.5s	remaining: 4.68s
243:	learn: 0.3773288	total: 1.51s	remaining: 4.67s
244:	learn: 0.3771715	total: 1.51s	remaining: 4.66s
245:	learn: 0.3769930	total: 1.52s	remaining: 4.66s
246:	learn: 0.3768920	total: 1.54s	remaining: 4.69s
247:	learn: 0.3767732	total: 1.55s	remaining: 4.7s
248:	learn: 0.3766633	total: 1.56s	remaining: 4.72s
249:	learn: 0.3765274	total: 1.58s	remaining: 4.74s
250:	learn: 0.3764335	total: 1.6s	remaining: 4.78s
251:	learn: 0.3763147	total: 1.63s	remaining: 4.84s
252:	learn: 0.3762256	total: 1.65s	remaining: 4.86s
253:	learn: 0.3760773	total: 1.66s	remaining: 4.88s
254:	learn: 0.3759522	total: 1.67s	remaining: 4.89s
255:	learn: 0.3758054	total: 1.7s	remaining: 4.93s
256:	learn: 0.3756553	total: 1.71s	remaining: 4.95s
257:	learn: 0.3755054	total: 1.72s	remaining: 4.95s
258:	learn: 0.3754219	total: 1.73s	remaining: 4.95s
259:	learn: 0.3752850	total: 1.74s	remaining: 4.96s
260:	learn: 0.3751234	total: 1.76s	remaining: 4.98s
261:	learn: 0.3749807	total: 1.77s	remaining: 4.98s
262:	learn: 0.3748217	total: 1.78s	remaining: 5s
263:	learn: 0.3747719	total: 1.8s	remaining: 5.03s
264:	learn: 0.3746304	total: 1.81s	remaining: 5.04s
265:	learn: 0.3745198	total: 1.83s	remaining: 5.06s
266:	learn: 0.3743213	total: 1.85s	remaining: 5.09s
267:	learn: 0.3741525	total: 1.87s	remaining: 5.11s
268:	learn: 0.3740220	total: 1.89s	remaining: 5.13s
269:	learn: 0.3738828	total: 1.89s	remaining: 5.12s
270:	learn: 0.3737486	total: 1.91s	remaining: 5.13s
271:	learn: 0.3736303	total: 1.92s	remaining: 5.14s
272:	learn: 0.3734164	total: 1.93s	remaining: 5.14s
273:	learn: 0.3732906	total: 1.94s	remaining: 5.14s
274:	learn: 0.3731894	total: 1.95s	remaining: 5.15s
275:	learn: 0.3729718	total: 1.96s	remaining: 5.15s
276:	learn: 0.3728434	total: 1.98s	remaining: 5.16s
277:	learn: 0.3727402	total: 2s	remaining: 5.19s
278:	learn: 0.3726836	total: 2.02s	remaining: 5.21s
279:	learn: 0.3725036	total: 2.02s	remaining: 5.21s
280:	learn: 0.3722884	total: 2.04s	remaining: 5.21s
281:	learn: 0.3721776	total: 2.05s	remaining: 5.22s
282:	learn: 0.3719567	total: 2.06s	remaining: 5.23s
283:	learn: 0.3718905	total: 2.09s	remaining: 5.26s
284:	learn: 0.3717519	total: 2.11s	remaining: 5.29s
285:	learn: 0.3715910	total: 2.12s	remaining: 5.29s
286:	learn: 0.3714735	total: 2.12s	remaining: 5.28s
287:	learn: 0.3713934	total: 2.14s	remaining: 5.28s
288:	learn: 0.3713411	total: 2.14s	remaining: 5.26s
289:	learn: 0.3712386	total: 2.15s	remaining: 5.27s
290:	learn: 0.3710849	total: 2.17s	remaining: 5.29s
291:	learn: 0.3710139	total: 2.19s	remaining: 5.32s
292:	learn: 0.3709288	total: 2.22s	remaining: 5.35s
293:	learn: 0.3708558	total: 2.23s	remaining: 5.36s
294:	learn: 0.3707837	total: 2.25s	remaining: 5.37s
295:	learn: 0.3706411	total: 2.27s	remaining: 5.39s
296:	learn: 0.3704381	total: 2.28s	remaining: 5.4s
297:	learn: 0.3702847	total: 2.29s	remaining: 5.4s
298:	learn: 0.3701746	total: 2.31s	remaining: 5.42s
299:	learn: 0.3700326	total: 2.33s	remaining: 5.43s
300:	learn: 0.3699364	total: 2.34s	remaining: 5.43s
301:	learn: 0.3697690	total: 2.35s	remaining: 5.42s
302:	learn: 0.3696722	total: 2.36s	remaining: 5.43s
303:	learn: 0.3695435	total: 2.38s	remaining: 5.44s
304:	learn: 0.3694513	total: 2.39s	remaining: 5.44s
305:	learn: 0.3693366	total: 2.42s	remaining: 5.48s
306:	learn: 0.3692191	total: 2.43s	remaining: 5.49s
307:	learn: 0.3691039	total: 2.46s	remaining: 5.52s
308:	learn: 0.3690054	total: 2.48s	remaining: 5.54s
309:	learn: 0.3687914	total: 2.5s	remaining: 5.56s
310:	learn: 0.3685262	total: 2.53s	remaining: 5.6s
311:	learn: 0.3683421	total: 2.54s	remaining: 5.61s
312:	learn: 0.3682421	total: 2.56s	remaining: 5.62s
313:	learn: 0.3680439	total: 2.58s	remaining: 5.64s
314:	learn: 0.3678816	total: 2.59s	remaining: 5.64s
315:	learn: 0.3676727	total: 2.61s	remaining: 5.65s
316:	learn: 0.3676270	total: 2.62s	remaining: 5.64s
317:	learn: 0.3674382	total: 2.63s	remaining: 5.65s
318:	learn: 0.3673475	total: 2.65s	remaining: 5.65s
319:	learn: 0.3672194	total: 2.66s	remaining: 5.65s
320:	learn: 0.3670782	total: 2.67s	remaining: 5.64s
321:	learn: 0.3669144	total: 2.68s	remaining: 5.63s
322:	learn: 0.3667793	total: 2.7s	remaining: 5.66s
323:	learn: 0.3666823	total: 2.72s	remaining: 5.67s
324:	learn: 0.3665231	total: 2.74s	remaining: 5.69s
325:	learn: 0.3664127	total: 2.75s	remaining: 5.69s
326:	learn: 0.3661515	total: 2.77s	remaining: 5.7s
327:	learn: 0.3660377	total: 2.79s	remaining: 5.72s
328:	learn: 0.3658759	total: 2.8s	remaining: 5.72s
329:	learn: 0.3657388	total: 2.82s	remaining: 5.72s
330:	learn: 0.3655737	total: 2.84s	remaining: 5.74s
331:	learn: 0.3654085	total: 2.87s	remaining: 5.78s
332:	learn: 0.3653351	total: 2.91s	remaining: 5.83s
333:	learn: 0.3651672	total: 2.95s	remaining: 5.89s
334:	learn: 0.3650038	total: 2.97s	remaining: 5.9s
335:	learn: 0.3649115	total: 2.99s	remaining: 5.91s
336:	learn: 0.3648416	total: 3.03s	remaining: 5.96s
337:	learn: 0.3647541	total: 3.04s	remaining: 5.96s
338:	learn: 0.3645345	total: 3.06s	remaining: 5.97s
339:	learn: 0.3643871	total: 3.09s	remaining: 6s
340:	learn: 0.3642484	total: 3.12s	remaining: 6.02s
341:	learn: 0.3641524	total: 3.15s	remaining: 6.05s
342:	learn: 0.3639878	total: 3.17s	remaining: 6.07s
343:	learn: 0.3638259	total: 3.19s	remaining: 6.09s
344:	learn: 0.3636588	total: 3.21s	remaining: 6.09s
345:	learn: 0.3635411	total: 3.22s	remaining: 6.08s
346:	learn: 0.3633687	total: 3.23s	remaining: 6.09s
347:	learn: 0.3632799	total: 3.25s	remaining: 6.08s
348:	learn: 0.3631715	total: 3.26s	remaining: 6.08s
349:	learn: 0.3630516	total: 3.27s	remaining: 6.08s
350:	learn: 0.3629255	total: 3.28s	remaining: 6.06s
351:	learn: 0.3627766	total: 3.28s	remaining: 6.05s
352:	learn: 0.3626945	total: 3.3s	remaining: 6.05s
353:	learn: 0.3625483	total: 3.31s	remaining: 6.04s
354:	learn: 0.3624206	total: 3.32s	remaining: 6.04s
355:	learn: 0.3622870	total: 3.34s	remaining: 6.04s
356:	learn: 0.3622209	total: 3.36s	remaining: 6.05s
357:	learn: 0.3621213	total: 3.39s	remaining: 6.08s
358:	learn: 0.3619497	total: 3.42s	remaining: 6.1s
359:	learn: 0.3617716	total: 3.42s	remaining: 6.09s
360:	learn: 0.3616572	total: 3.45s	remaining: 6.11s
361:	learn: 0.3615204	total: 3.47s	remaining: 6.11s
362:	learn: 0.3613547	total: 3.49s	remaining: 6.12s
363:	learn: 0.3611822	total: 3.5s	remaining: 6.12s
364:	learn: 0.3610764	total: 3.52s	remaining: 6.13s
365:	learn: 0.3608706	total: 3.54s	remaining: 6.12s
366:	learn: 0.3608192	total: 3.55s	remaining: 6.13s
367:	learn: 0.3606190	total: 3.56s	remaining: 6.12s
368:	learn: 0.3604777	total: 3.58s	remaining: 6.13s
369:	learn: 0.3603789	total: 3.6s	remaining: 6.14s
370:	learn: 0.3602720	total: 3.62s	remaining: 6.13s
371:	learn: 0.3601240	total: 3.63s	remaining: 6.13s
372:	learn: 0.3600267	total: 3.65s	remaining: 6.14s
373:	learn: 0.3599046	total: 3.67s	remaining: 6.14s
374:	learn: 0.3597115	total: 3.69s	remaining: 6.15s
375:	learn: 0.3596119	total: 3.71s	remaining: 6.16s
376:	learn: 0.3593624	total: 3.73s	remaining: 6.16s
377:	learn: 0.3592864	total: 3.74s	remaining: 6.16s
378:	learn: 0.3592227	total: 3.76s	remaining: 6.17s
379:	learn: 0.3590386	total: 3.77s	remaining: 6.16s
380:	learn: 0.3589651	total: 3.79s	remaining: 6.16s
381:	learn: 0.3588904	total: 3.8s	remaining: 6.15s
382:	learn: 0.3587861	total: 3.82s	remaining: 6.15s
383:	learn: 0.3586810	total: 3.83s	remaining: 6.15s
384:	learn: 0.3586630	total: 3.84s	remaining: 6.13s
385:	learn: 0.3584621	total: 3.86s	remaining: 6.14s
386:	learn: 0.3582488	total: 3.88s	remaining: 6.14s

CatBoostClassifier()

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1180,  131],
       [ 224,  223]])

In [ ]:
#accuracy
accuracy_score(y_test,y_pred)*100

79.806598407281

In [ ]:
#Gradient boosting
from sklearn.ensemble import GradientBoostingClassifier
model=GradientBoostingClassifier()
model.fit(x_train,y_train)

GradientBoostingClassifier()

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'Yes', 'No', 'No'], dtype=object)

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1194,  117],
       [ 218,  229]])

In [ ]:
#accuracy
accuracy_score(y_test,y_pred)*100

80.94425483503981

In [ ]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

model=XGBClassifier()

le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
#prediction
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
#confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[1165,  146],
       [ 211,  236]])

In [ ]:
#accuracy
accuracy_score(y_test,y_pred)*100

79.69283276450511

In [ ]:
#upto here classification models completed

In [ ]:
#Regression Models

import pandas as pd